// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wrts.Models;

namespace wrts.Migrations
{
    [DbContext(typeof(WRTSDbContext))]
    [Migration("20221210193522_foreign_key vehicle_id")]
    partial class foreign_keyvehicle_id
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("wrts.Models.Ramp", b =>
                {
                    b.Property<int>("Ramp_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Vehicle_ID")
                        .HasColumnType("int");

                    b.Property<int?>("VehiclesVehicle_ID")
                        .HasColumnType("int");

                    b.HasKey("Ramp_ID");

                    b.HasIndex("VehiclesVehicle_ID");

                    b.ToTable("Ramps");
                });

            modelBuilder.Entity("wrts.Models.Vehicles", b =>
                {
                    b.Property<int>("Vehicle_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Vehicle_Type_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("arrival_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("citizenship_number")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("company_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("departure_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("driver_language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("driver_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("driver_surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("vehicle_status")
                        .HasColumnType("int");

                    b.Property<int>("waybill_number")
                        .HasColumnType("int");

                    b.HasKey("Vehicle_ID");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("wrts.Models.Ramp", b =>
                {
                    b.HasOne("wrts.Models.Vehicles", "Vehicles")
                        .WithMany()
                        .HasForeignKey("VehiclesVehicle_ID");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
